In [110]:
import interview_questions, warm_up
import random
import datetime
import pandas as pd
import numpy as np
import torch
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

In [111]:
df = pd.read_csv('06-26-2020.csv') # dataset for coding warmup
df.to_sql('june_corona', con=engine)
questions = interview_questions.questions
warmUp = warm_up.questions
data = [q for q in questions.items()]
warmUpQuestions = [q for q in warmUp.items()]

In [112]:
# join warmups
url1 = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-31-2020.csv'
url2 = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-27-2020.csv'

In [113]:
#day1 = pd.read_csv(url1)
#day2 = pd.read_csv(url2)

In [114]:
results = {}

def trackAnswers(result, question):
    datetime_object = datetime.datetime.now()
    if result:
        results[datetime_object] = (question, 'T')
    results[datetime_object] = (question, 'T')

# add in some probability questions
def quiz_question():
    q = data[random.randint(0,2)]
    print(q[0])
    answer = input()
    if answer == q[1]:
        print('good job', trackAnswers(True, q[0]))
    else:    
        print(f'wrong answer {q[1]}', trackAnswers(False, q[0]))

# make it so this does not repeat questions
# add in some probability questions
def warm_up_question():
    for n,i in enumerate(range(5)):
        q = warmUpQuestions[random.randint(0,14)]
        print(str(n+1) + " " + q[1] + '\n')

In [115]:
#quiz_question()
#engine.execute("SELECT Admin2 FROM june_corona").fetchall()

##### Warm-up

In [116]:
warm_up_question()

1 rename index and column name

2 create a vector and matrix in pytorch and numpy

3 assign the columns, index, and data to varaibles and display

4 rename index and column name

5 return the summary statistics of the column



In [117]:
df.columns

Index(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key', 'Incidence_Rate', 'Case-Fatality_Ratio'],
      dtype='object')

In [119]:
df.rename(index={0:'zero'},columns={'Admin2':'admind2'}).head(2)

FIPS    admind2  Province_State Country_Region          Last_Update  \
zero  45001.0  Abbeville  South Carolina             US  2020-06-27 04:33:35   
1     22001.0     Acadia       Louisiana             US  2020-06-27 04:33:35   

            Lat      Long_  Confirmed  Deaths  Recovered  Active  \
zero  34.223334 -82.461707        100       0          0     100   
1     30.295065 -92.414197        783      36          0     747   

                       Combined_Key  Incidence_Rate  Case-Fatality_Ratio  
zero  Abbeville, South Carolina, US      407.713948             0.000000  
1             Acadia, Louisiana, US     1261.987267             4.597701

In [132]:
engine.execute(
    '''
    alter table june_corona
    rename column Admin2 to admin2;
    '''
).fetchall()

[]

In [135]:
torch.tensor([0,0,1])

tensor([0, 0, 1])

In [136]:
np.array([0,1,1])

array([0, 1, 1])

In [137]:
np.array([[0,1],[1,0]])

array([[0, 1],
       [1, 0]])

In [138]:
torch.tensor([[0,1],[1,0]])

tensor([[0, 1],
        [1, 0]])

In [140]:
df.index.to_numpy()

array([   0,    1,    2, ..., 3785, 3786, 3787])

In [141]:
df.columns

Index(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key', 'Incidence_Rate', 'Case-Fatality_Ratio'],
      dtype='object')

In [148]:
df.to_numpy()[2][2]

'Virginia'

In [153]:
df.head(2)

FIPS     Admin2  Province_State Country_Region          Last_Update  \
0  45001.0  Abbeville  South Carolina             US  2020-06-27 04:33:35   
1  22001.0     Acadia       Louisiana             US  2020-06-27 04:33:35   

         Lat      Long_  Confirmed  Deaths  Recovered  Active  \
0  34.223334 -82.461707        100       0          0     100   
1  30.295065 -92.414197        783      36          0     747   

                    Combined_Key  Incidence_Rate  Case-Fatality_Ratio  
0  Abbeville, South Carolina, US      407.713948             0.000000  
1          Acadia, Louisiana, US     1261.987267             4.597701

In [169]:
engine.execute(
    '''
    select 'total',
        sum(deaths),
        sum(confirmed)
    from june_corona
    union
    select 'average',
        avg(deaths),
        avg(Confirmed)
    from june_corona
    union
    select 'min',
        min(deaths),
        min(Confirmed)
    from june_corona
    union
    select 'max',
        max(deaths),
        max(Confirmed)
    from june_corona
    '''
).fetchall()

[('average', 130.46224920802536, 2590.8513727560717),
 ('max', 38888, 258508),
 ('min', 0, 0),
 ('total', 494191, 9814145)]