In [33]:
import interview_questions, warm_up
import random
import datetime
import pandas as pd
import numpy as np
import torch

In [2]:
df = pd.read_csv('06-26-2020.csv') # dataset for coding warmup
questions = interview_questions.questions
warmUp = warm_up.questions
data = [q for q in questions.items()]
warmUpQuestions = [q for q in warmUp.items()]

In [10]:
results = {}

def trackAnswers(result, question):
    datetime_object = datetime.datetime.now()
    if result:
        results[datetime_object] = (question, 'T')
    results[datetime_object] = (question, 'T')

# add in some probability questions
def quiz_question():
    q = data[random.randint(0,2)]
    print(q[0])
    answer = input()
    if answer == q[1]:
        print('good job', trackAnswers(True, q[0]))
    else:    
        print(f'wrong answer {q[1]}', trackAnswers(False, q[0]))

# make it so this does not repeat questions
# add in some probability questions
def warm_up_question():
    for n,i in enumerate(range(5)):
        q = warmUpQuestions[random.randint(0,14)]
        print(str(n+1) + " " + q[1] + '\n')

In [8]:
quiz_question()

what is a type 1 error
False positive: reject the null hypothesis when it is actually true. You test negative for coronavirus when don't have it
wrong answer false positive: rejecting the null hypothesis when it’s actually true. The test result says you have coronavirus, but you actually don’t None


##### Warm-up

In [11]:
warm_up_question()

1 return unique values from the column, and the frequencies of values in the column

2 return the summary statistics of the column

3 select the same column with loc and iloc, and then print out all types in the column

4 create a vector and matrix in pytorch and numpy

5 find the size and shape of the data



In [16]:
import torch
M = torch.tensor([[0,1],[1,0]])
R = torch.tensor([[1,0],[1,1]])
torch.matmul(M,R)

tensor([[1, 1],
        [1, 0]])

In [17]:
df.head(1)

FIPS     Admin2  Province_State Country_Region          Last_Update  \
0  45001.0  Abbeville  South Carolina             US  2020-06-27 04:33:35   

         Lat      Long_  Confirmed  Deaths  Recovered  Active  \
0  34.223334 -82.461707        100       0          0     100   

                    Combined_Key  Incidence_Rate  Case-Fatality_Ratio  
0  Abbeville, South Carolina, US      407.713948                  0.0

In [23]:
df.iloc[:,2].describe()

count      3619
unique      550
top       Texas
freq        246
Name: Province_State, dtype: object

In [25]:
df.loc[:,'Deaths'].describe()

count     3788.000000
mean       130.462249
std       1075.882839
min          0.000000
25%          0.000000
50%          2.000000
75%         18.000000
max      38888.000000
Name: Deaths, dtype: float64

In [26]:
df.loc[:,'Deaths'].head(2)

0     0
1    36
Name: Deaths, dtype: int64

In [27]:
df.iloc[:,2].head(2)

0    South Carolina
1         Louisiana
Name: Province_State, dtype: object

In [28]:
df.loc[:,'Deaths'].dtypes

dtype('int64')

In [29]:
torch.tensor([1,0,0])

tensor([1, 0, 0])

In [34]:
np.array([1,0,0])

array([1, 0, 0])

In [35]:
torch.tensor([[1,0,0],[0,0,1]])

tensor([[1, 0, 0],
        [0, 0, 1]])

In [37]:
np.array([[1,0,1],[0,0,1]])

array([[1, 0, 1],
       [0, 0, 1]])

In [40]:
df.size

(3788, 14)

In [60]:
def mySum(*args):
    result = 0
    for arg in args:
        result += arg
        
    return result

def myAvg(*args):
    tmp,cnt = 0,[]
    for i,arg in enumerate(args):
        tmp += arg
        cnt = i+1
        
    return tmp/cnt
    

In [61]:
myAvg(10,20,30,40,50)

30.0

In [43]:
mySum(*[10,20,30])

60