In [9]:
import interview_questions, warm_up
import random
import datetime
import pandas as pd
import numpy as np
import torch
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

In [10]:
df = pd.read_csv('06-26-2020.csv') # dataset for coding warmup
df.to_sql('june_corona', con=engine)
questions = interview_questions.questions
warmUp = warm_up.questions
data = [q for q in questions.items()]
warmUpQuestions = [q for q in warmUp.items()]

In [3]:
# join warmups
url1 = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-31-2020.csv'
url2 = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/12-27-2020.csv'

In [5]:
#day1 = pd.read_csv(url1)
#day2 = pd.read_csv(url2)

In [6]:
results = {}

def trackAnswers(result, question):
    datetime_object = datetime.datetime.now()
    if result:
        results[datetime_object] = (question, 'T')
    results[datetime_object] = (question, 'T')

# add in some probability questions
def quiz_question():
    q = data[random.randint(0,2)]
    print(q[0])
    answer = input()
    if answer == q[1]:
        print('good job', trackAnswers(True, q[0]))
    else:    
        print(f'wrong answer {q[1]}', trackAnswers(False, q[0]))

# make it so this does not repeat questions
# add in some probability questions
def warm_up_question():
    for n,i in enumerate(range(5)):
        q = warmUpQuestions[random.randint(0,14)]
        print(str(n+1) + " " + q[1] + '\n')

In [11]:
#quiz_question()
#engine.execute("SELECT Admin2 FROM june_corona").fetchall()

##### Warm-up

In [8]:
warm_up_question()

1 make a dataframe from a list and a dictionary

2 display the dataframe's data types, value_counts, and info

3 multiple two matrices in pytorch

4 create a column/delete a column

5 create a vector and matrix in pytorch and numpy



In [33]:
l = list(range(10))
d = {'A': [chr(v) for v in range(65,75)]}

In [42]:
df.columns

Index(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key', 'Incidence_Rate', 'Case-Fatality_Ratio'],
      dtype='object')

In [36]:
df.dtypes

FIPS                   float64
Admin2                  object
Province_State          object
Country_Region          object
Last_Update             object
Lat                    float64
Long_                  float64
Confirmed                int64
Deaths                   int64
Recovered                int64
Active                   int64
Combined_Key            object
Incidence_Rate         float64
Case-Fatality_Ratio    float64
dtype: object

In [45]:
# add this guy & one for & look up how to just get US values w/conditionals in this case
# equivalent in sql
df.groupby('Country_Region')['Province_State'].value_counts()

Country_Region  Province_State                              
Australia       Australian Capital Territory                    1
                New South Wales                                 1
                Northern Territory                              1
                Queensland                                      1
                South Australia                                 1
                                                               ..
United Kingdom  Saint Helena, Ascension and Tristan da Cunha    1
                Scotland                                        1
                Turks and Caicos Islands                        1
                Unknown                                         1
                Wales                                           1
Name: Province_State, Length: 563, dtype: int64

In [75]:
engine.execute(
    "SELECT Country_Region, count(Province_State) \
    FROM june_corona \
    GROUP BY Country_Region order by Province_State desc;"
).fetchall()

[('US', 3114),
 ('France', 10),
 ('Denmark', 2),
 ('Ukraine', 27),
 ('Sweden', 21),
 ('Germany', 17),
 ('Pakistan', 7),
 ('Australia', 8),
 ('Netherlands', 4),
 ('Chile', 17),
 ('China', 34),
 ('United Kingdom', 16),
 ('India', 36),
 ('Spain', 20),
 ('Peru', 26),
 ('Colombia', 34),
 ('Canada', 15),
 ('Japan', 48),
 ('Mexico', 32),
 ('Russia', 83),
 ('Brazil', 27),
 ('Italy', 21),
 ('Zimbabwe', 0),
 ('Zambia', 0),
 ('Yemen', 0),
 ('West Bank and Gaza', 0),
 ('Vietnam', 0),
 ('Venezuela', 0),
 ('Uzbekistan', 0),
 ('Uruguay', 0),
 ('United Arab Emirates', 0),
 ('Uganda', 0),
 ('Turkey', 0),
 ('Tunisia', 0),
 ('Trinidad and Tobago', 0),
 ('Togo', 0),
 ('Timor-Leste', 0),
 ('Thailand', 0),
 ('Tanzania', 0),
 ('Tajikistan', 0),
 ('Taiwan*', 0),
 ('Syria', 0),
 ('Switzerland', 0),
 ('Suriname', 0),
 ('Sudan', 0),
 ('Sri Lanka', 0),
 ('South Sudan', 0),
 ('South Africa', 0),
 ('Somalia', 0),
 ('Slovenia', 0),
 ('Slovakia', 0),
 ('Singapore', 0),
 ('Sierra Leone', 0),
 ('Seychelles', 0),
 ('Ser

In [54]:
M = torch.tensor([[1,0],[0,0]])
N = torch.tensor([[1,0],[0,0]])

torch.matmul(M,N)

tensor([[1, 0],
        [0, 0]])

In [66]:
# display two cols at once
df['newCol'] = [chr(v) for v in range(df.shape[0])]
df.loc[:,['newCol','Country_Region']].head(1)


newCol Country_Region
0                   US

In [67]:
df.drop(columns='newCol')

FIPS        Admin2  Province_State Country_Region  \
0     45001.0     Abbeville  South Carolina             US   
1     22001.0        Acadia       Louisiana             US   
2     51001.0      Accomack        Virginia             US   
3     16001.0           Ada           Idaho             US   
4     19001.0         Adair            Iowa             US   
...       ...           ...             ...            ...   
3783      NaN           NaN             NaN         Zambia   
3784      NaN           NaN             NaN       Zimbabwe   
3785   2066.0  Copper River          Alaska             US   
3786   2063.0       Chugach          Alaska             US   
3787      NaN           NaN         Unknown          China   

              Last_Update        Lat       Long_  Confirmed  Deaths  \
0     2020-06-27 04:33:35  34.223334  -82.461707        100       0   
1     2020-06-27 04:33:35  30.295065  -92.414197        783      36   
2     2020-06-27 04:33:35  37.767072  -75.632346       1037      14   
3     2020-06-27 04:33:35  43.452658 -116.241552       1585      23   
4     2020-06-27 03:33:36  41.330756  -94.471059         14       0   
...                   ...        ...         ...        ...     ...   
3783  2020-06-27 04:33:35 -13.133897   27.849332       1531      21   
3784  2020-06-27 04:33:35 -19.015438   29.154857        561       6   
3785  2021-04-02 15:13:53  60.388600 -162.890520          1       0   
3786  2021-04-02 15:13:53  61.166660 -149.900000         18       0   
3787  2020-06-27 04:33:35        NaN         NaN          0       0   

      Recovered  Active                   Combined_Key  Incidence_Rate  \
0             0     100  Abbeville, South Carolina, US      407.713948   
1             0     747          Acadia, Louisiana, US     1261.987267   
2             0    1023         Accomack, Virginia, US     3208.936750   
3             0    1562                 Ada, Idaho, US      329.120180   
4             0      14                Adair, Iowa, US      195.749441   
...         ...     ...                            ...             ...   
3783       1233     277                         Zambia        8.327914   
3784        135     420                       Zimbabwe        3.774492   
3785          0       0       Copper River, Alaska, US             NaN   
3786          0       0            Chugach, Alaska, US             NaN   
3787          0       0                 Unknown, China        0.000000   

      Case-Fatality_Ratio  
0                0.000000  
1                4.597701  
2                1.350048  
3                1.451104  
4                0.000000  
...                   ...  
3783             1.371653  
3784             1.069519  
3785                  NaN  
3786                  NaN  
3787             0.000000  

[3788 rows x 14 columns]

In [68]:
torch.tensor([1,0,0])

tensor([1, 0, 0])

In [69]:
np.array([1,0,0])

array([1, 0, 0])