In [6]:
import numpy as np
import torch
import sympy

##### Question 1

In [15]:
A = sympy.Matrix([[1,0,-2,-3],
                  [0,1,-2,-1]])
A_T = A.T

In [32]:
B = sympy.Matrix([[2,2,1,0],
                  [3,1,0,1]])

A.nullspace()

[Matrix([
 [2],
 [2],
 [1],
 [0]]),
 Matrix([
 [3],
 [1],
 [0],
 [1]])]

In [33]:
B = sympy.Matrix([[1,2,5,0,5],
                  [3,1,15,2,2],
                  [2,0,4,3,2]
                 ])

B

Matrix([
[1, 2,  5, 0, 5],
[3, 1, 15, 2, 2],
[2, 0,  4, 3, 2]])

In [34]:
B.rref()

(Matrix([
 [1, 0, 0, 59/30,  9/5],
 [0, 1, 0,  -2/5, 13/5],
 [0, 0, 1, -7/30, -2/5]]),
 (0, 1, 2))

In [39]:
9/5

1.8

In [24]:
Anp = np.array([[1,0,-2,-3],
                [0,1,-2,-1]])

Bnp = np.array([[1,0,0,0],
                [0,1,0,0]])

In [30]:
2*-1.5

-3.0

In [20]:
sympy.mulA.T

Matrix([
[14, 7],
[ 7, 6]])

In [179]:
E_21 = torch.tensor([[1,0,0],[1,1,0],[0,0,1]])
A = torch.tensor([[2,1,0],[-2,0,1],[8,5,3]])

In [190]:
E_21

tensor([[1, 0, 0],
        [1, 1, 0],
        [0, 0, 1]])

In [180]:
torch.matmul(E_21,A)

tensor([[2, 1, 0],
        [0, 1, 1],
        [8, 5, 3]])

In [181]:
E_31 = torch.tensor([[1,0,0],[0,1,0],[-4,0,1]])
A = torch.tensor([[2,1,0],[-2,0,1],[8,5,3]])

In [182]:
torch.matmul(E_31,A)

tensor([[ 2,  1,  0],
        [-2,  0,  1],
        [ 0,  1,  3]])

In [191]:
E = torch.matmul(E_21,E_31)
E

tensor([[ 1,  0,  0],
        [ 1,  1,  0],
        [-4,  0,  1]])

In [192]:
torch.matmul(E,A)

tensor([[2, 1, 0],
        [0, 1, 1],
        [0, 1, 3]])

In [167]:
# example from lecture: elmininate x and y to make upper triangular
# b is the last column in the augmented matrix
E_21 = torch.tensor([[1,0,0],[-2,1,0],[1,0,1]])
A = torch.tensor([[2,4,-2,2],[4,9,-3,8],[-2,-3,7,10]])
E_32 = torch.tensor([[1,0,0],[0,1,0],[0,-1,1]])

In [168]:
# solving system of linear equations using matrix multiplication
torch.matmul(E_32,torch.matmul(E_21,A))

tensor([[ 2,  4, -2,  2],
        [ 0,  1,  1,  4],
        [ 0,  0,  4,  8]])

In [106]:
# example from lecture: elmininate x and y to make upper triangular
# b is the last column in the augmented matrix
E = torch.tensor([[1,0,0],[-3,1,0],[-2,0,1]])
A = torch.tensor([[1,3,5,1,0,0],[3,10,17,0,1,0],[2,8,3,0,0,1]])

In [107]:
# pivot first column
A_1 = torch.matmul(E,A); A_1

tensor([[ 1,  3,  5,  1,  0,  0],
        [ 0,  1,  2, -3,  1,  0],
        [ 0,  2, -7, -2,  0,  1]])

In [108]:
# pivot second column
E2 = E = torch.tensor([[1,0,0],[0,1,0],[0,-2,1]])
A_2 = torch.matmul(E2,A_1); A_2

tensor([[  1,   3,   5,   1,   0,   0],
        [  0,   1,   2,  -3,   1,   0],
        [  0,   0, -11,   4,  -2,   1]])

In [109]:
A_2[2:3]/-11

tensor([[-0.0000, -0.0000,  1.0000, -0.3636,  0.1818, -0.0909]])

###### Question 2

In [204]:
A = torch.tensor([[0,0,0,2,1,0,0,0.],
                  [0,0,3,0,0,1,0,0.],
                  [0,4,0,0,0,0,1,0.],
                  [5,0,0,0,0,0,0,1.]])

_A_ = torch.tensor([[0,0,0,2.],
                    [0,0,3,0.],
                    [0,4,0,0.],
                    [5,0,0,0.]])


In [205]:
np.linalg.inv(_A_)

array([[0.        , 0.        , 0.        , 0.2       ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.33333334, 0.        , 0.        ],
       [0.5       , 0.        , 0.        , 0.        ]], dtype=float32)

In [220]:
E = torch.tensor([[0,0,0,.2],
                  [0,0,.25,0.],
                  [0,.333,0,0.],
                  [0.5,0,0,0.]])

In [221]:
torch.matmul(E,A)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2000],
        [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2500, 0.0000],
        [0.0000, 0.0000, 0.9990, 0.0000, 0.0000, 0.3330, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000, 0.5000, 0.0000, 0.0000, 0.0000]])

In [222]:
np.dot(E,A)

array([[1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.2  ],
       [0.   , 1.   , 0.   , 0.   , 0.   , 0.   , 0.25 , 0.   ],
       [0.   , 0.   , 0.999, 0.   , 0.   , 0.333, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 1.   , 0.5  , 0.   , 0.   , 0.   ]],
      dtype=float32)

In [225]:
w = np.array([0,0,0,5])
u = np.array([0,0,0,1])

In [226]:
np.dot(w,u)

5

In [227]:
A = torch.tensor([[3,2,0,0,1,0,0,0.],
                  [4,3,0,0,0,1,0,0.],
                  [0,0,6,5,0,0,1,0.],
                  [0,0,7,-6,0,0,0,1.]])

A

tensor([[ 3.,  2.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 4.,  3.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  6.,  5.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  7., -6.,  0.,  0.,  0.,  1.]])

In [254]:
E = torch.tensor([[1,0,0,0.],
                  [-(4/3),1,0,0.],
                  [0,0,1,0.],
                  [0,0,-(7/6),1.]])
E

tensor([[ 1.0000,  0.0000,  0.0000,  0.0000],
        [-1.3333,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0000,  0.0000],
        [ 0.0000,  0.0000, -1.1667,  1.0000]])

In [255]:
torch.matmul(E,A)

tensor([[  3.0000,   2.0000,   0.0000,   0.0000,   1.0000,   0.0000,   0.0000,
           0.0000],
        [  0.0000,   0.3333,   0.0000,   0.0000,  -1.3333,   1.0000,   0.0000,
           0.0000],
        [  0.0000,   0.0000,   6.0000,   5.0000,   0.0000,   0.0000,   1.0000,
           0.0000],
        [  0.0000,   0.0000,   0.0000, -11.8333,   0.0000,   0.0000,  -1.1667,
           1.0000]])

###### Question 3

In [88]:
A = torch.tensor([[2,-1,0.],
                  [-1,2,-1.],
                  [0,-1,2.]])
A

tensor([[ 2., -1.,  0.],
        [-1.,  2., -1.],
        [ 0., -1.,  2.]])

In [89]:
E1 = torch.tensor([[1,0,0.],
                   [0.5,1,0.],
                   [1/3,2/3,1.]
                  ])
E1

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 1.0000, 0.0000],
        [0.3333, 0.6667, 1.0000]])

In [91]:
# calc U
U = torch.matmul(E1,A); A1

tensor([[ 2.0000, -1.0000,  0.0000],
        [ 0.0000,  1.5000, -1.0000],
        [ 0.0000,  0.0000,  1.3333]])

In [109]:
L.T

tensor([[ 1.0000, -0.5000,  0.0000],
        [ 0.0000,  1.0000, -0.6667],
        [-0.0000, -0.0000,  1.0000]])

In [110]:
L

tensor([[ 1.0000,  0.0000, -0.0000],
        [-0.5000,  1.0000, -0.0000],
        [ 0.0000, -0.6667,  1.0000]])

In [97]:
# calc E1
L = torch.inverse(E1)
print(L)

# check
torch.matmul(L,U)

tensor([[ 1.0000,  0.0000, -0.0000],
        [-0.5000,  1.0000, -0.0000],
        [ 0.0000, -0.6667,  1.0000]])


tensor([[ 2., -1.,  0.],
        [-1.,  2., -1.],
        [ 0., -1.,  2.]])

In [103]:
# make D by adding diagnols
D = torch.tensor([[2,0,0],
                  [0,1.5,0],
                  [0,0,1.3333]
                 ])

In [108]:
# now you have LDL^T

A_final = torch.matmul(L,torch.matmul(D,L.T)); A_final

tensor([[ 2.0000, -1.0000,  0.0000],
        [-1.0000,  2.0000, -1.0000],
        [ 0.0000, -1.0000,  2.0000]])

In [124]:
A = torch.tensor([[1,0.,0.],
                  [0,1.,0.],
                  [0,3.,1.]
               ])

In [125]:
B = torch.tensor([[1,0.,0.],
                  [2,1.,0.],
                  [0,0.,1.]
               ])

In [126]:
torch.inverse(torch.matmul(A,B))

tensor([[ 1.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.0000e+00,  1.0000e+00,  0.0000e+00],
        [ 1.7881e-07, -3.0000e+00,  1.0000e+00]])