In [1]:
import numpy as np
import torch

##### Question 1

Supposed $A,B,C$ are square matrices and $AB = BC$. Is it true that $B = C$?

No!

In [2]:
A = np.array([[1,1],
              [1,1]])
B = np.array([[1,0],
              [0,1]])
C = np.array([[0,1],
              [1,0]])

In [3]:
np.matmul(A,B)

array([[1, 1],
       [1, 1]])

In [4]:
np.matmul(A,C)

array([[1, 1],
       [1, 1]])

but $B \neq C$

##### Question 2

Is it true that $(A+B)^2 = A^2+2AB+B^2$

No!

In [5]:
A = np.array([[0,1],
              [1,0]])

B = np.array([[0,2],
              [3,0]])

In [6]:
np.matmul((A+B),(A+B))

array([[12,  0],
       [ 0, 12]])

In [7]:
np.matmul(A,A) + 2*np.matmul(A,B) + np.matmul(B,B)

array([[13,  0],
       [ 0, 11]])

###### Question 3

In [122]:
A = torch.tensor([[3,1,0.],
                  [6,3,2.],
                  [0,3,3.]
                 ])

A

tensor([[3., 1., 0.],
        [6., 3., 2.],
        [0., 3., 3.]])

In [123]:
E1 = torch.tensor([[1,0,0.],
                  [-2,1,0.],
                  [0,0,1.]
                 ])

E1

tensor([[ 1.,  0.,  0.],
        [-2.,  1.,  0.],
        [ 0.,  0.,  1.]])

In [124]:
A1 = torch.matmul(E,A); A1

tensor([[3., 1., 0.],
        [0., 1., 2.],
        [0., 3., 3.]])

In [125]:
E2 = torch.tensor([[1,0,0.],
                  [0,1,0.],
                  [0,-3,1.]
                 ])

torch.matmul(E2,A1)

tensor([[ 3.,  1.,  0.],
        [ 0.,  1.,  2.],
        [ 0.,  0., -3.]])

In [128]:
E = torch.matmul(E2,E1); E

tensor([[ 1.,  0.,  0.],
        [-2.,  1.,  0.],
        [ 6., -3.,  1.]])

In [129]:
torch.matmul(E,A)

tensor([[ 3.,  1.,  0.],
        [ 0.,  1.,  2.],
        [ 0.,  0., -3.]])

In [132]:
np.linalg.inv(E)

array([[1., 0., 0.],
       [2., 1., 0.],
       [0., 3., 1.]], dtype=float32)

In [133]:
torch.inverse(E)

tensor([[1.0000e+00, -0.0000e+00, 0.0000e+00],
        [2.0000e+00, 1.0000e+00, 0.0000e+00],
        [1.7881e-07, 3.0000e+00, 1.0000e+00]])

##### Question 4

In [2]:
A = torch.tensor([[1,1,1.],
                  [2,4,5.],
                  [0,4,0.]
                 ])

A

tensor([[1., 1., 1.],
        [2., 4., 5.],
        [0., 4., 0.]])

In [32]:
E1 = torch.tensor([[1,0,0.],
                  [-2,1,0.],
                  [0,0,1.]
                 ])

E1

tensor([[ 1.,  0.,  0.],
        [-2.,  1.,  0.],
        [ 0.,  0.,  1.]])

In [33]:
A1 = torch.matmul(E1,A); A1

tensor([[1., 1., 1.],
        [0., 2., 3.],
        [0., 4., 0.]])

In [36]:
E2 = torch.tensor([[1,0,0.],
                  [0,1,0.],
                  [0,-2,1.]
                 ])

E2

tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0., -2.,  1.]])

In [37]:
A2 = torch.matmul(E2,A1); A2

tensor([[ 1.,  1.,  1.],
        [ 0.,  2.,  3.],
        [ 0.,  0., -6.]])

In [57]:
E = torch.matmul(E2,E1); E

tensor([[ 1.,  0.,  0.],
        [-2.,  1.,  0.],
        [ 4., -2.,  1.]])

In [58]:
E_1 = torch.inverse(E); E_1

tensor([[1., -0., 0.],
        [2., 1., 0.],
        [0., 2., 1.]])

In [43]:
torch.matmul(E_1,A2)

tensor([[1., 1., 1.],
        [2., 4., 5.],
        [0., 4., 0.]])

In [47]:
D = torch.tensor([[1,0,0.],
                  [0,2,0.],
                  [0,0,-6.]
                 ])

D

tensor([[ 1.,  0.,  0.],
        [ 0.,  2.,  0.],
        [ 0.,  0., -6.]])

In [55]:
A3 = torch.tensor([[1,1,1.],
                  [0,1,3/2.],
                  [0,0,1.]
                 ])

A3

tensor([[1.0000, 1.0000, 1.0000],
        [0.0000, 1.0000, 1.5000],
        [0.0000, 0.0000, 1.0000]])

In [56]:
torch.matmul(E_1,torch.matmul(D,A3))

tensor([[1., 1., 1.],
        [2., 4., 5.],
        [0., 4., 0.]])