In [1]:
import numpy
import torch

In [29]:
A = torch.tensor([[4.,2.],[8.,3.]]); A

tensor([[4., 2.],
        [8., 3.]])

In [30]:
I = torch.tensor([[1.,0.],[0.,1.]]); I

tensor([[1., 0.],
        [0., 1.]])

In [31]:
A[:1]/4

tensor([[1.0000, 0.5000]])

In [32]:
A[:1] = A[:1]/4; A

tensor([[1.0000, 0.5000],
        [8.0000, 3.0000]])

In [33]:
I[:1] = I[:1]/4; I

tensor([[0.2500, 0.0000],
        [0.0000, 1.0000]])

In [42]:
A[1:2] = A[1:2]-8 * A[:1]; A

tensor([[ 1.0000,  0.5000],
        [ 0.0000, -1.0000]])

In [44]:
I[1:2] = I[1:2]-8*I[:1]; I

tensor([[ 0.2500,  0.0000],
        [-2.0000,  1.0000]])

In [45]:
A[1:2] = A[1:2]/-1; A

tensor([[1.0000, 0.5000],
        [-0.0000, 1.0000]])

In [46]:
I[1:2] = I[1:2]/-1; I

tensor([[ 0.2500,  0.0000],
        [ 2.0000, -1.0000]])

In [48]:
A[:1] = A[:1] - 0.5 * A[1:2]; A

tensor([[1., 0.],
        [-0., 1.]])

In [50]:
I[:1] = I[:1] - 0.5 * I[1:2]; I

tensor([[-0.7500,  0.5000],
        [ 2.0000, -1.0000]])

In [51]:
A

tensor([[1., 0.],
        [-0., 1.]])

##### Problem Set

In [85]:
A = torch.tensor([[1.,3.],[2.,5.]]); A

tensor([[1., 3.],
        [2., 5.]])

In [86]:
A_aug = torch.tensor([[1.,3.,1.,0.],[2.,5.,0.,1.]]); A_aug

tensor([[1., 3., 1., 0.],
        [2., 5., 0., 1.]])

In [87]:
A_aug[1:2] = A_aug[1:2] + -2*(A_aug[:1]) ; A_aug

tensor([[ 1.,  3.,  1.,  0.],
        [ 0., -1., -2.,  1.]])

In [92]:
A_aug[1:2] = A_aug[1:2]/-1; A_aug

tensor([[ 1.,  3.,  1.,  0.],
        [-0.,  1.,  2., -1.]])

In [95]:
A_aug[:1] = A_aug[:1] + -3*A_aug[1:2]; A_aug

tensor([[ 1.,  0., -5.,  3.],
        [-0.,  1.,  2., -1.]])