In [3]:
import numpy as np

In [53]:
V = np.array([[1,0,1],
               [2,1,3],
               [0,3,3]])

b = np.array([1,0,0])

V

array([[1, 0, 1],
       [2, 1, 3],
       [0, 3, 3]])

In [42]:
A = V[:,[0,1]]

_A_ = np.dot(A.T,A)

_A_

array([[ 5,  2],
       [ 2, 10]])

In [52]:
ATA = np.dot(np.dot(A,np.linalg.inv(_A_)),A.T); ATA

array([[ 0.2173913 ,  0.39130435, -0.13043478],
       [ 0.39130435,  0.80434783,  0.06521739],
       [-0.13043478,  0.06521739,  0.97826087]])

In [56]:
e = b - np.dot(ATA,b); e

array([ 0.7826087 , -0.39130435,  0.13043478])

In [74]:
np.dot(e.T,A)

array([1.11022302e-16, 1.11022302e-16])

In [67]:
np.dot(np.array([0,0,4]),np.array([[1,1],
                                   [0,1],
                                   [0,0]]))

array([0, 0])

In [75]:
I = np.array([[1,0,0],
           [0,1,0],
           [0,0,1]])

I - ATA

array([[ 0.7826087 , -0.39130435,  0.13043478],
       [-0.39130435,  0.19565217, -0.06521739],
       [ 0.13043478, -0.06521739,  0.02173913]])