In [7]:
import numpy as np
import torch

In [3]:
A = np.array([[2,-3],[-4,6]])
B = np.array([[8,4],[5,5]])
C = np.array([[5,-2],[3,1]])

In [4]:
A.dot(B)

array([[ 1, -7],
       [-2, 14]])

In [6]:
A.dot(C)

array([[ 1, -7],
       [-2, 14]])

In [13]:
A_t = torch.tensor([[2.,-3.],[-4.,6.]])
B_t = torch.tensor([[8.,4.],[5.,5.]])
C_t = torch.tensor([[5.,-2.],[3.,1.]])

In [15]:
torch.matmul(A_t, B_t)

tensor([[ 1., -7.],
        [-2., 14.]])

In [16]:
torch.matmul(A_t, C_t)

tensor([[ 1., -7.],
        [-2., 14.]])

In [54]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[4,5],[6,7]])

In [55]:
torch.matmul(A,B)

tensor([[16, 19],
        [36, 43]])

In [56]:
torch.matmul(B,A)

tensor([[19, 28],
        [27, 40]])

In [57]:
(A+B)**2

tensor([[ 25,  49],
        [ 81, 121]])

In [60]:
(A**2)+(2*(A*B))+(B**2)

tensor([[ 25,  49],
        [ 81, 121]])

##### Using inverse to solve system of linear equations

In [21]:
X = np.array([[4,2],[-5,-3]]); X

array([[ 4,  2],
       [-5, -3]])

In [18]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [19]:
y = np.array([4,-7])
y

array([ 4, -7])

In [20]:
w = np.dot(Xinv, y); w

array([-1.,  4.])

In [22]:
np.dot(X,w)

array([ 4., -7.])

##### In Pytorch

In [34]:
X_t = torch.tensor([[4, 2], [-5, -3.]])

In [36]:
Xinv_t = torch.inverse(X_t); Xinv_t

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [40]:
y_t = torch.tensor([4, -7.]); y_t

tensor([ 4., -7.])

In [42]:
w_t = torch.matmul(Xinv_t, y_t); w_t

tensor([-1.,  4.])

In [44]:
torch.matmul(X_t,w_t)

tensor([ 4., -7.])

##### Find the inverse of [1,3],[2,5]

In [63]:
torch.inverse(torch.tensor([[1,3],[2,5.]]))

tensor([[-5.,  3.],
        [ 2., -1.]])

##### Factor A

In [66]:
A = torch.tensor([[3,1,0],[6,3,2],[0,3,3.]]); A

tensor([[3., 1., 0.],
        [6., 3., 2.],
        [0., 3., 3.]])

In [67]:
A_LU, pivots = torch.lu(A)

In [68]:
A_LU

tensor([[ 6.0000,  3.0000,  2.0000],
        [ 0.0000,  3.0000,  3.0000],
        [ 0.5000, -0.1667, -0.5000]])

In [69]:
pivots

tensor([2, 3, 3], dtype=torch.int32)