In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
X = np.array([[25,2],
              [5,26],
              [3,7]])

X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [6]:
X_pt = torch.tensor([[25,2],
                     [5,26],
                     [3,7]
                    ])

X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [4]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [5]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [7]:
X_pt+2

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [8]:
X_pt*2

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [9]:
X_pt*2+2 #python operators are overloaded

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [10]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [11]:
# Hadamard Product

In [14]:
A = X+2; A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [15]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [16]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [19]:
A_pt = X_pt + 2; A_pt

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [20]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [22]:
# tensor reduction


In [23]:
X.sum()

68

In [24]:
torch.sum(X_pt)

tensor(68)