In [5]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
X = np.array([[25,2],
              [5,26],
              [3,7]])

X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [6]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

In [8]:
X_pt = torch.tensor([[25,2],
                     [5,26],
                     [3,7]
                    ])
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])