In [21]:
import numpy as np
import torch
import tensorflow as tf

In [6]:
x = np.array([25,2,5], dtype=np.float16); x

array([25.,  2.,  5.], dtype=float16)

In [7]:
len(x)

3

In [8]:
x.shape

(3,)

In [9]:
type(x)

numpy.ndarray

In [10]:
x[0]

25.0

In [11]:
type(x[0])

numpy.float16

In [12]:
# transposing a reg 1D array has no effect
x_t = x.T; x_t

array([25.,  2.,  5.], dtype=float16)

In [13]:
x_t.shape

(3,)

In [14]:
# nested "matrix-style" brackets
y = np.array([[25,2,5]]); y

array([[25,  2,  5]])

In [15]:
y.shape

(1, 3)

In [16]:
y_t = y.T; y_t

array([[25],
       [ 2],
       [ 5]])

In [17]:
y_t.shape

(3, 1)

In [18]:
# got back to original shape
y_t.T.shape

(1, 3)

In [19]:
# zero vectors
z = np.zeros(3); z

array([0., 0., 0.])

In [22]:
x_pt = torch.tensor([25,2,5]); x_pt

tensor([25,  2,  5])

In [23]:
x_tf = tf.Variable([25,2,5]); x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

##### Norms

In [25]:
# L2 norm from scratch
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [26]:
np.linalg.norm(x)

25.58

In [27]:
# L1 norm
np.abs(25) + np.abs(2) + np.abs(5)

32

In [28]:
# squared L2 norm
(25**2 + 2**2 + 5**2)

654

In [29]:
np.dot(x,x)

654.0

In [32]:
# Max norm/Linf Norm
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

##### generalized Lp Norm
||x||_p = (sum_i|x_i|^p)^1/p