In [1]:
import numpy as np

In [2]:
X = np.array([[25,2],[5,26],[3,7]]); X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [6]:
# first row
X[:,0]

array([25,  5,  3])

In [7]:
# middle row
X[1,:]

array([ 5, 26])

In [8]:
X[0:2,0:2]

array([[25,  2],
       [ 5, 26]])

In [9]:
import torch

In [10]:
X_pt = torch.tensor([[25,2],[5,26],[3,7]]); X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [11]:
X_pt.shape

torch.Size([3, 2])

In [12]:
X_pt[1,:]

tensor([ 5, 26])

In [14]:
import tensorflow as tf

In [15]:
X_tf = tf.Variable([[25,2],[5,26],[3,7]]); X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [16]:
# rank 0 = scalar
# rank 1 = vector
# rank 2 = matrix
tf.rank(X_tf) # rank 2: all matrices are

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [17]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>